/*let arr = ["delhi","mumbai","praygraj"];
arr.forEach((val,indx) => {
    console.log(val.toUpperCase(),"=",indx); //value => item ,indx => position ,array
});*/

/*
let ary = ["ddt","ggt","ggh","jjk","oop"]

ary.forEach((val,indx)=>{
    console.log(val.toUpperCase(),"=",indx)
})*/

let arr = ["ffgt","jjk","kkj","llp"];

arr.forEach((val,indx,arr)=>{
    console.log(val.toUpperCase(),"=",indx,arr);
})

//for each function only use for java

// for interview 
// question => WHAT IS HIGHER ORDER FUNCTION 
// => FOREACH IS CALLED HIGER ORDER FUNCTION OR HIGHER ORDER METHOD
// => ARE THOSE FUNCTION TAKE OTHER  FUNCTION AS PARAMETER
// => OR RETURN ANY FUNCTION AS THERE OUTPUT